### ISSUE TITLE
0.10.0 Install guide refers an old kuadrant-operator-catalog.

### ISSUE THREAD

**Issue by leathersole** [Kuadrant/docs.kuadrant.io#137]
In [Step 6 - Create secrets for your credentials](https://docs.kuadrant.io/0.10.0/kuadrant-operator/doc/install/install-openshift/#step-6-create-secrets-for-your-credentials), kuadrant-operator-catalog refers `v0.7.1`. Should this be `0.10.0`?

```
kubectl apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kuadrant-operator-catalog
  namespace: kuadrant-system
spec:
  sourceType: grpc
  image: quay.io/kuadrant/kuadrant-operator-catalog:v0.7.1
  displayName: Kuadrant Operators
  publisher: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
EOF
```

**Comment by leathersole** [comment]
I'll add other issues in the install guide to this ticket.
[Step 7 - Install the Kuadrant Operator](https://docs.kuadrant.io/0.10.0/kuadrant-operator/doc/install/install-openshift/#step-7-install-the-kuadrant-operator)
`preview` isn't valid value for `Subscription.spec.channel`, it should be `stable`.
```
kubectl apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: kuadrant-system
spec:
  channel: preview
  installPlanApproval: Automatic
  name: kuadrant-operator
  source: kuadrant-operator-catalog
  sourceNamespace: kuadrant-system
---
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: kuadrant
  namespace: kuadrant-system
spec:
  upgradeStrategy: Default
EOF
```
[Step 8 - Configure Kuadrant](https://docs.kuadrant.io/0.10.0/kuadrant-operator/doc/install/install-openshift/#step-8-configure-kuadrant)
`spec.limitador` isn't valid field name.
```
kubectl apply -f - <<EOF
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
spec:
  limitador:
    storage:
      redis-cached:
        configSecretRef:
          name: redis-config
EOF
```
